server:
  port: 9002


spring:
  application:
    name: PROJECT-SERVICE
  datasource:
    url: jdbc:mysql://rm-bp16730aq4j29ys9y5o.mysql.rds.aliyuncs.com:3306/lgh-project?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
lgh:
  swagger:
    title: 项目管理服务
    description: 项目管理服务接口文档